server:
  port: 8079
spring:
  application:
    name: matrikelapplication

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: PLAIN-9092://localhost:9092
  h2:
    console:
      enabled: true
      path: /h2-console
user:
  timezone: UTC

kfs:
  cqrs:
    topicnames: event.dataengineer.inventory.eventstore
    eventobjectsPackages:
      - dk.ksf.application
    producingActorId: KS
