server:
  port: 8081
spring:
  application:
    name: kafkatestapplication
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: PLAIN-9092://localhost:9092
  h2:
    console:
      enabled: true

