POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1409",
  "fornavn": "Hans",
  "efternavn": "Henriksen"
}

###
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1411",
  "fornavn": "Jørgen",
  "efternavn": "Jensen-Hansen"
}

###
PUT http://localhost:8081/commands/klient/021165-1411
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1411",
  "fornavn": "Jørgen",
  "efternavn": "Jensen-Hansen-jensen"
}


###
PUT http://localhost:8081/commands/klient/021165-1409
Content-Type: application/json
requestId: transId2

{
  "fornavn": "Hans Peter Bondesen",
  "efternavn": "Jensens"
}

### Hent klienter fra readmodel
GET http://localhost:8081/readmodel/klienter
Content-Type: application/json
requestId: transId2


### Hent klienter fra writemodel
GET http://localhost:8081/writemodel/klienter
Content-Type: application/json
requestId: transId2

###

GET http://localhost:8081/writemodel/klienter/eventstore
Content-Type: application/json
requestId: transId2

