POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1409",
  "fornavn": "Hans",
  "efternavn": "Henriksen"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1411",
  "fornavn": "Jørgen",
  "efternavn": "Jensen-Hansen"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1413",
  "fornavn": "Niels",
  "efternavn": "Hemmingsen"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1415",
  "fornavn": "Frank",
  "efternavn": "Pedersen"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1417",
  "fornavn": "Søren",
  "efternavn": "Nielsen"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1419",
  "fornavn": "Jørgen",
  "efternavn": "Dietrich"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1420",
  "fornavn": "Lone",
  "efternavn": "Dietrich"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1423",
  "fornavn": "Ole",
  "efternavn": "Rode"
}


### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1426",
  "fornavn": "Ellen",
  "efternavn": "Munch"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1429",
  "fornavn": "Jesper",
  "efternavn": "XXX"
}

### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1431",
  "fornavn": "Jesper",
  "efternavn": "Skibby"
}


### Opret klient
POST http://localhost:8081/commands/klient
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1428",
  "fornavn": "Dorthe",
  "efternavn": "Holm"
}


### Ret klient
PUT http://localhost:8081/commands/klient/021165-1419
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1419",
  "fornavn": "Jørgensen",
  "efternavn": "Dietrichsen",
  "version": 13
}

###
PUT http://localhost:8081/commands/klient/021165-1411
Content-Type: application/json
requestId: transI1

{
  "cpr": "021165-1411",
  "fornavn": "Jørgen Niels-Peter",
  "efternavn": "Jensen"
}


###
PUT http://localhost:8081/commands/klient/021165-1409
Content-Type: application/json
requestId: transId2

{
  "fornavn": "Hans Peter",
  "efternavn": "Hansen"
}

### Hent klienter fra readmodel
GET http://localhost:8081/readmodel/klienter
Content-Type: application/json
requestId: transId2


### Hent klienter fra writemodel
GET http://localhost:8081/writemodel/klienter
Content-Type: application/json
requestId: transId2

### Show the event-store
GET http://localhost:8081/writemodel/klienter/eventstore
Content-Type: application/json
requestId: transId2

### Create Snapshots
POST http://localhost:8081/writemodel/snapshots
Content-Type: application/json
requestId: transId2
